import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'chat',
  nodes: [
    ...commonNodes(),
    n(
      'recipient',
      'client',
      'Recipient Client',
      'client',
      5,
      'Receives messages and emits delivery or read receipts.',
      'A second endpoint makes delivery distinct from acceptance.',
      'An offline device cannot acknowledge immediately.',
    ),
    n(
      'connection',
      'realtime',
      'Connection Gateway',
      'network',
      1,
      'Maintains long-lived bidirectional sessions.',
      'Push messages without repeated polling.',
      'Reconnects require session and cursor recovery.',
      'HOT PATH',
    ),
    n(
      'service',
      'services',
      'Message Router',
      'compute',
      2,
      'Validates membership, deduplicates message IDs, and orders channel writes.',
      'Retries should preserve one logical message.',
      'Ordering is scoped to a channel, not globally.',
    ),
    n(
      'presence',
      'cache',
      'Presence / Sessions',
      'data',
      3,
      'Maps users to live connections.',
      'Route to active sessions or choose offline delivery.',
      'Presence is a best-effort, expiring signal.',
    ),
    n(
      'database',
      'database',
      'Message Store',
      'data',
      3,
      'Persists channel history before accepting delivery.',
      'A gateway failure must not lose accepted messages.',
      'Busy channels can create hot partitions.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'fanout',
      'workers',
      'Channel Fanout',
      'compute',
      4,
      'Distributes an accepted message to subscribed sessions.',
      'Group delivery grows independently of the write path.',
      'Large channels require backpressure.',
    ),
    n(
      'notify',
      'notifications',
      'Offline Push',
      'events',
      4,
      'Signals offline devices that durable messages are waiting.',
      'Push is a wake-up hint, not the message history.',
      'Providers can delay or drop notifications.',
    ),
    n(
      'storage',
      'storage',
      'Attachment Store',
      'data',
      4,
      'Stores attachment bytes behind authorized references.',
      'Keep binary payloads out of channel history.',
      'Link lifetime and access checks must agree.',
    ),
  ],
  scenarios: [
    flow(
      'send-message',
      'Send Message',
      'Persist before acknowledging, then deliver to an online or offline recipient.',
      'Accepted, delivered, and read are different states.',
      [
        s(
          'client',
          'connection',
          'Send message ID',
          'A client sends a stable ID over its persistent session.',
          'Reconnect retries may repeat a send.',
          'Duplicate message effects.',
        ),
        s(
          'connection',
          'service',
          'Route to the channel',
          'Check membership and channel ordering.',
          'Only authorized members can send.',
          'Cross-channel data leaks.',
        ),
        s(
          'service',
          'database',
          'Persist message',
          'Commit the channel message before confirming acceptance.',
          'A volatile connection is not durable storage.',
          'Accepted messages disappearing.',
          'write',
        ),
        s(
          'database',
          'client',
          'Accepted acknowledgment',
          'The sender sees a durable acceptance acknowledgment.',
          'Acceptance does not mean the other device has received it.',
          'Ambiguous delivery status.',
          'ack',
        ),
        s(
          'service',
          'presence',
          'Locate recipient sessions',
          'Read expiring session mappings.',
          'Delivery strategy depends on current connectivity.',
          'Blind fanout.',
          'read',
        ),
        s(
          'presence',
          'fanout',
          'Online recipient',
          'An active session is available.',
          'Route live delivery to its owning gateway.',
          'Polling overhead.',
          'event',
          { excludeWhen: ['offline'] },
        ),
        s(
          'fanout',
          'recipient',
          'Deliver live message',
          'Push the accepted message to the recipient.',
          'The persistent session enables low-latency updates.',
          'Delayed conversation.',
          'event',
          { excludeWhen: ['offline'] },
        ),
        s(
          'recipient',
          'client',
          'Delivery receipt',
          'A receipt reports device delivery, not human reading.',
          'Different states need different acknowledgments.',
          'False read confirmation.',
          'ack',
          { excludeWhen: ['offline'] },
        ),
        s(
          'service',
          'notify',
          'Recipient offline',
          'Send only a wake-up notification; retain message history.',
          'An offline recipient has no active socket.',
          'Lost delivery on disconnect.',
          'event',
          { condition: 'offline' },
        ),
        s(
          'recipient',
          'database',
          'Fetch missed history',
          'On reconnect, resume from the last acknowledged cursor.',
          'Push notifications are not a durable queue.',
          'Gaps after offline periods.',
          'read',
          { condition: 'offline' },
        ),
        s(
          'database',
          'recipient',
          'Apply recovered messages',
          'Return committed messages after the cursor; apply each message ID once.',
          'Fetching history is not delivery until the device receives and applies it.',
          'Premature delivery receipts.',
          'ack',
          { condition: 'offline' },
        ),
        s(
          'recipient',
          'client',
          'Recovered delivery receipt',
          'Acknowledge device delivery after the recovered history has been applied.',
          'Delivery is distinct from reading the conversation.',
          'Incorrect sender status.',
          'ack',
          { condition: 'offline' },
        ),
      ],
      ['normal', 'offline'],
    ),
    flow(
      'group-message',
      'Group Message',
      'Fan one durable write out to multiple live sessions.',
      'Group delivery is parallel; ordering and deduplication stay channel-scoped.',
      [
        s(
          'client',
          'service',
          'Submit group message',
          'Validate membership and the stable message ID.',
          'Groups need the same authorization as direct messages.',
          'Unauthorized sends.',
        ),
        s(
          'service',
          'database',
          'Commit channel sequence',
          'Persist before distribution.',
          'Fanout should never race an uncommitted message.',
          'Phantom delivery.',
          'write',
        ),
        s(
          'database',
          'events',
          'Publish accepted message',
          'Relay the durable message event.',
          'Workers can retry independently.',
          'Gateway coupling.',
          'event',
        ),
        s(
          'events',
          'fanout',
          'Consumer falls behind',
          'Accepted messages remain durable while a busy fanout consumer catches up from its checkpoint.',
          'Backpressure protects downstream sessions.',
          'Dropping messages under load.',
          'event',
          { condition: 'consumer-lag', duration: 6000 },
        ),
        s(
          'events',
          'fanout',
          'Resolve group sessions',
          'Partition a large recipient set into bounded work.',
          'A hot channel must not monopolize workers.',
          'Fanout overload.',
          'event',
        ),
        s(
          'fanout',
          'recipient',
          'Deliver to recipient',
          'Push to a subscribed session.',
          'Recipients should not wait for each other.',
          'Head-of-line blocking.',
          'event',
          { parallelGroup: 'group-delivery' },
        ),
        s(
          'fanout',
          'client',
          'Sync sender’s devices',
          'Deliver the same logical message to the sender’s subscriptions.',
          'Multiple devices need a consistent history.',
          'Device divergence.',
          'event',
          { parallelGroup: 'group-delivery' },
        ),
      ],
      ['normal', 'consumer-lag'],
    ),
    flow(
      'reconnect',
      'Reconnect Client',
      'Resume from a durable cursor after the socket disappears.',
      'Connection state is ephemeral; message history is durable.',
      [
        s(
          'recipient',
          'connection',
          'Reconnect session',
          'Authenticate a new connection after network recovery.',
          'Old gateway state may no longer exist.',
          'Stale sessions.',
        ),
        s(
          'connection',
          'presence',
          'Register current session',
          'Replace the expiring route to this device.',
          'Future pushes must use the live gateway.',
          'Routing into a dead connection.',
          'write',
        ),
        s(
          'recipient',
          'database',
          'Resume from cursor',
          'Read missing channel messages after the last acknowledged sequence.',
          'Network delivery can be interrupted at any point.',
          'History gaps.',
          'read',
        ),
        s(
          'database',
          'recipient',
          'Apply and deduplicate',
          'Merge recovered messages by stable ID before advancing the cursor.',
          'Live delivery can overlap recovery reads.',
          'Duplicates during catch-up.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'discord',
      name: 'Discord',
      summary:
        'Public 2023 message storage details inside a conceptual connection and delivery model. No end-to-end encryption claim is made.',
      era: 'Message storage migration: March 2023',
      sources: [sources.discord],
      overrides: {
        'rw-database': {
          label: 'ScyllaDB Message Store',
          technology: 'ScyllaDB',
          confidence: 'verified',
          sourceIds: ['discord'],
          description:
            'Discord documented ScyllaDB storage partitioned by channel and time bucket in 2023; this is historical evidence.',
        },
        'rw-service': {
          label: 'Message Data Service',
          technology: 'Rust data services (2023)',
          confidence: 'inferred',
          sourceIds: ['discord'],
          description:
            'Rust data services are documented; this model combines routing and validation responsibilities for teaching.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
