import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'commerce',
  nodes: [
    ...commonNodes(),
    n(
      'service',
      'services',
      'Order / Saga Coordinator',
      'compute',
      2,
      'Tracks checkout progress and compensating actions.',
      'Inventory and payment do not share one database transaction.',
      'Compensation is a business action, not time travel.',
      'CONSISTENCY BOUNDARY',
    ),
    n(
      'inventory',
      'database',
      'Inventory Reservations',
      'data',
      3,
      'Reserves available units with expiry and conditional writes.',
      'Prevent concurrent checkouts from overselling.',
      'Reservations reduce stock available to other shoppers.',
    ),
    n(
      'payment',
      'services',
      'Payment Adapter',
      'compute',
      3,
      'Authorizes funds using a stable order payment key.',
      'Retries must refer to the same payment attempt.',
      'Timeout does not prove failure.',
    ),
    n(
      'database',
      'database',
      'Order Store / Outbox',
      'data',
      4,
      'Commits order state and outgoing events together.',
      'Downstream fulfillment must reflect a durable order.',
      'Outbox delivery is at least once.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'catalog',
      'database',
      'Product Catalog',
      'data',
      3,
      'Stores current product attributes and pricing.',
      'Search results are not authoritative checkout data.',
      'Catalog updates may reach indexes later.',
    ),
    n(
      'search',
      'search',
      'Product Search',
      'data',
      2,
      'Retrieves indexed product candidates.',
      'Discovery needs text ranking and filters.',
      'Search freshness is eventually consistent.',
    ),
    n(
      'cart',
      'database',
      'Cart Store',
      'data',
      3,
      'Stores shopper intent before checkout.',
      'A cart should survive device and service failures.',
      'Cart contents do not reserve inventory.',
    ),
    n(
      'fulfillment',
      'workers',
      'Fulfillment',
      'compute',
      5,
      'Allocates shipping work for confirmed orders.',
      'Warehouse latency must not hold open checkout.',
      'Duplicate events require deduplication.',
    ),
  ],
  scenarios: [
    flow(
      'place-order',
      'Place Order',
      'Coordinate stock and payment without pretending there is a global transaction.',
      'A saga records progress and compensates completed work after failure.',
      [
        s(
          'client',
          'gateway',
          'Submit checkout key',
          'Send the cart and a stable checkout key.',
          'The user may retry after a lost response.',
          'Duplicate orders.',
        ),
        s(
          'gateway',
          'service',
          'Begin order saga',
          'Create or resume the order attempt.',
          'Every stage needs a durable state.',
          'Untraceable partial checkout.',
        ),
        s(
          'service',
          'inventory',
          'Reserve stock',
          'Conditionally reserve the requested units.',
          'Availability can change after browsing.',
          'Overselling.',
          'write',
        ),
        s(
          'inventory',
          'service',
          'Reservation rejected',
          'Record insufficient inventory and stop before payment.',
          'An unavailable item cannot be fulfilled.',
          'Charging an impossible order.',
          'ack',
          { condition: 'inventory-failure' },
        ),
        s(
          'service',
          'client',
          'Report unavailable stock',
          'Return a terminal rejection for this attempt.',
          'The shopper needs an actionable outcome.',
          'Endless retry ambiguity.',
          'ack',
          { condition: 'inventory-failure' },
        ),
        s(
          'service',
          'payment',
          'Authorize payment',
          'Use the order payment key to deduplicate authorization.',
          'Network retries must not reserve funds twice.',
          'Duplicate financial effects.',
          'request',
          { excludeWhen: ['inventory-failure'] },
        ),
        s(
          'payment',
          'service',
          'Processor outcome uncertain',
          'A timeout leaves authorization status unknown.',
          'A missing reply is not a decline.',
          'Unsafe blind retry.',
          'ack',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'payment',
          'Reconcile the attempt',
          'Query the same attempt; in this branch, a late authorization is found and voided.',
          'Resolve the external effect before closing checkout.',
          'An orphaned authorization.',
          'request',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'inventory',
          'Release reservation',
          'Compensate after the payment attempt is resolved and canceled.',
          'Stock should become available again.',
          'Leaked reservations.',
          'write',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'client',
          'Checkout canceled safely',
          'Report cancellation after compensation.',
          'A failed saga must have an explicit terminal state.',
          'Misleading success.',
          'ack',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'database',
          'Confirm order and outbox',
          'Persist the successful order only after reservation and authorization.',
          'Durable state defines what fulfillment may do.',
          'Shipping unconfirmed orders.',
          'write',
          { excludeWhen: ['inventory-failure', 'payment-timeout'] },
        ),
        s(
          'database',
          'events',
          'Relay order confirmed',
          'Publish the committed event with retries.',
          'Avoid an unsafe database/broker dual write.',
          'Lost fulfillment work.',
          'event',
          {
            excludeWhen: ['inventory-failure', 'payment-timeout'],
            parallelGroup: 'confirm-and-relay',
          },
        ),
        s(
          'service',
          'client',
          'Order confirmed',
          'Return the durable order reference.',
          'Confirmation is distinct from shipment and settlement.',
          'Ambiguous order status.',
          'ack',
          {
            excludeWhen: ['inventory-failure', 'payment-timeout'],
            parallelGroup: 'confirm-and-relay',
          },
        ),
        s(
          'events',
          'fulfillment',
          'Schedule fulfillment',
          'Deduplicate by order ID and prepare shipment.',
          'Warehouse work is independent of checkout latency.',
          'Coupled availability.',
          'event',
          { excludeWhen: ['inventory-failure', 'payment-timeout'] },
        ),
      ],
      ['normal', 'inventory-failure', 'payment-timeout'],
    ),
    flow(
      'search-product',
      'Search Product',
      'Use an index for discovery, then hydrate current product details.',
      'An index accelerates discovery but does not own price or stock.',
      [
        s(
          'client',
          'search',
          'Search the catalog',
          'Submit text and filters.',
          'Product discovery is not a primary-key lookup.',
          'Slow catalog scans.',
        ),
        s(
          'search',
          'catalog',
          'Hydrate top products',
          'Fetch authoritative attributes for matched IDs.',
          'Index copies can lag product updates.',
          'Stale displayed facts.',
          'read',
        ),
        s(
          'catalog',
          'client',
          'Return product cards',
          'Render current details with search ordering.',
          'Ranking and product truth have separate owners.',
          'Inconsistent discovery.',
          'ack',
        ),
      ],
    ),
    flow(
      'add-cart',
      'Add to Cart',
      'Persist purchase intent without claiming inventory is reserved.',
      'A durable cart is not a stock guarantee.',
      [
        s(
          'client',
          'gateway',
          'Add selected item',
          'Send product ID and intended quantity.',
          'Clients should not determine authoritative prices.',
          'Price tampering.',
        ),
        s(
          'gateway',
          'cart',
          'Merge cart change',
          'Persist the requested item update.',
          'Concurrent devices may change the same cart.',
          'Lost shopper intent.',
          'write',
        ),
        s(
          'cart',
          'client',
          'Return cart state',
          'Show saved items; stock is checked at checkout.',
          'A wishlist-like cart cannot hold stock indefinitely.',
          'False availability guarantees.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'amazon',
      name: 'Amazon-style',
      summary:
        'A teaching checkout saga, with historical Dynamo cart evidence. This is not a claim about Amazon’s current checkout topology.',
      era: 'Dynamo paper: 2007; checkout conceptual',
      sources: [sources.amazon],
      overrides: {
        'rw-cart': {
          label: 'Dynamo Cart Store · 2007',
          technology: 'Dynamo (historical)',
          confidence: 'verified',
          sourceIds: ['amazon'],
          description:
            'The 2007 Dynamo paper describes shopping-cart use. Current service choices are not established by that paper.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
