import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'files',
  nodes: [
    ...commonNodes(),
    n(
      'device',
      'client',
      'Second Device',
      'client',
      5,
      'Maintains a local file tree and last-applied change cursor.',
      'Sync must resume after offline periods.',
      'Concurrent edits can conflict.',
    ),
    n(
      'chunks',
      'client',
      'Chunker / Content Hash',
      'client',
      1,
      'Splits bytes and computes hashes on the device.',
      'Reuse unchanged blocks across versions.',
      'Chunking policy affects deduplication efficiency.',
    ),
    n(
      'service',
      'services',
      'Upload / Sync Coordinator',
      'compute',
      2,
      'Authorizes transfers and checks which blocks already exist.',
      'Separate small metadata operations from bulk byte transfer.',
      'Cross-user deduplication must not leak file existence.',
    ),
    n(
      'storage',
      'storage',
      'Immutable Block Store',
      'data',
      3,
      'Stores content-addressed blocks durably.',
      'Unchanged bytes need not be uploaded again.',
      'Garbage collection must respect all live versions.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'metadata',
      'database',
      'Metadata / Versions',
      'data',
      3,
      'Atomically commits paths, permissions, and block references.',
      'A file should point only to acknowledged blocks.',
      'Metadata and byte durability have separate boundaries.',
      'CONSISTENCY BOUNDARY',
    ),
    n(
      'changes',
      'database',
      'Change Log',
      'data',
      4,
      'Records ordered metadata changes for resumable device sync.',
      'Devices need deltas, not repeated full listings.',
      'Retention must account for long-offline devices.',
    ),
    n(
      'conflicts',
      'services',
      'Conflict Resolver',
      'compute',
      2,
      'Detects stale base versions and preserves conflicting edits.',
      'Silent overwrite can lose user work.',
      'Automatic merges are not safe for every file format.',
    ),
  ],
  scenarios: [
    flow(
      'upload-file',
      'Upload File',
      'Upload missing blocks, then atomically publish the new file version.',
      'Durable bytes come first; metadata commit makes a version visible.',
      [
        s(
          'client',
          'chunks',
          'Chunk and hash',
          'Compute content hashes for the local file blocks.',
          'Identify reusable content before transfer.',
          'Redundant bandwidth.',
        ),
        s(
          'chunks',
          'service',
          'Check missing blocks',
          'Send authorized hashes and intended file metadata.',
          'A deduplication check must respect account boundaries.',
          'Unsafe existence leaks.',
        ),
        s(
          'service',
          'client',
          'Return upload plan',
          'Authorize only the missing block transfers.',
          'Unchanged chunks can be reused.',
          'Whole-file reuploads.',
          'ack',
        ),
        s(
          'client',
          'storage',
          'Upload missing bytes directly',
          'Transfer missing blocks to durable storage.',
          'The API coordinator should not proxy file bytes.',
          'Central bandwidth bottlenecks.',
          'write',
        ),
        s(
          'storage',
          'client',
          'Acknowledge durable blocks',
          'Confirm checksum and required durability before commit.',
          'An upload acknowledgment must be meaningful.',
          'Metadata pointing to absent content.',
          'ack',
        ),
        s(
          'client',
          'metadata',
          'Commit file version',
          'Conditionally write the block list, path, permissions, and base version.',
          'Concurrent writers need conflict detection.',
          'Lost updates.',
          'write',
        ),
        s(
          'metadata',
          'changes',
          'Append committed change',
          'Record the metadata change transactionally.',
          'Sync events must correspond to visible versions.',
          'Invisible or phantom edits.',
          'write',
        ),
        s(
          'changes',
          'device',
          'Notify another device',
          'Deliver a hint to fetch changes from its cursor.',
          'Hints can be lost; the log is the durable recovery path.',
          'Missed sync after disconnect.',
          'event',
        ),
        s(
          'device',
          'changes',
          'Resume change cursor',
          'Ask for committed changes since the last applied position.',
          'The device may have been offline.',
          'Missed notifications.',
          'read',
        ),
        s(
          'changes',
          'device',
          'Return version references',
          'Send changed paths and block lists with a new cursor.',
          'Metadata identifies exactly which bytes form a version.',
          'Inconsistent local files.',
          'ack',
        ),
        s(
          'device',
          'storage',
          'Download missing blocks',
          'Fetch blocks absent from the local cache.',
          'Most edits leave much content unchanged.',
          'Wasteful full downloads.',
          'read',
        ),
        s(
          'storage',
          'device',
          'Verify and apply',
          'Verify hashes, assemble the file, then advance the cursor.',
          'A crash must not acknowledge a partially applied change.',
          'Corrupted or skipped sync.',
          'ack',
        ),
      ],
    ),
    flow(
      'sync-device',
      'Sync Device',
      'Read change metadata and fetch only missing blocks.',
      'Sync notifications are hints; cursors and hashes make recovery reliable.',
      [
        s(
          'device',
          'changes',
          'Resume change cursor',
          'Ask for committed changes since the last applied position.',
          'The device may have been offline.',
          'Missed notifications.',
          'read',
        ),
        s(
          'changes',
          'device',
          'Return version references',
          'Send changed paths and block lists with a new cursor.',
          'Metadata identifies exactly which bytes form a version.',
          'Inconsistent local files.',
          'ack',
        ),
        s(
          'device',
          'storage',
          'Download missing blocks',
          'Fetch blocks absent from the local cache.',
          'Most edits leave much content unchanged.',
          'Wasteful full downloads.',
          'read',
        ),
        s(
          'storage',
          'device',
          'Verify and apply',
          'Verify hashes, assemble the file, then advance the cursor.',
          'A crash must not acknowledge a partially applied change.',
          'Corrupted or skipped sync.',
          'ack',
        ),
      ],
    ),
    flow(
      'resolve-conflict',
      'Resolve Conflict',
      'Preserve two edits based on the same old version.',
      'Detect a stale base version instead of silently overwriting data.',
      [
        s(
          'device',
          'metadata',
          'Commit stale-base edit',
          'Submit an edit whose base version has already changed.',
          'Offline devices can edit concurrently.',
          'Assuming a single writer.',
          'write',
        ),
        s(
          'metadata',
          'conflicts',
          'Reject conflicting commit',
          'Compare the supplied base version with the current version.',
          'Conditional commits expose write races.',
          'Silent lost updates.',
        ),
        s(
          'conflicts',
          'metadata',
          'Preserve conflict copy',
          'Store both versions or a format-aware merge result.',
          'Arbitrary binary files cannot be safely auto-merged.',
          'Destruction of user edits.',
          'write',
        ),
        s(
          'metadata',
          'device',
          'Report conflict resolution',
          'Return the preserved version and conflict status.',
          'The user needs to know which version is current.',
          'Hidden divergence.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'dropbox',
      name: 'Dropbox',
      summary:
        'Historical Magic Pocket block storage inside a conceptual chunking, metadata, and device-sync flow.',
      era: 'Magic Pocket publication: 2016',
      sources: [sources.dropbox],
      overrides: {
        'rw-storage': {
          label: 'Magic Pocket Blocks',
          technology: 'Magic Pocket (2016)',
          confidence: 'verified',
          sourceIds: ['dropbox'],
          description:
            'Dropbox documented immutable, content-addressed block storage in Magic Pocket. The surrounding sync boundaries here are modeled.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
