import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'gaming',
  nodes: [
    ...commonNodes(),
    n(
      'peer',
      'client',
      'Other Player',
      'client',
      5,
      'Interpolates authoritative snapshots and predicts local input.',
      'Smooth rendering must tolerate network jitter.',
      'Prediction can be corrected by the server.',
    ),
    n(
      'service',
      'services',
      'Lobby / Matchmaking',
      'compute',
      2,
      'Groups eligible players by region and match constraints.',
      'A good match balances wait time and fairness.',
      'Tighter constraints increase queue time.',
    ),
    n(
      'allocator',
      'infrastructure',
      'Regional Session Allocator',
      'operations',
      3,
      'Reserves capacity and issues a session endpoint and join token.',
      'Gameplay needs a nearby server with tick capacity.',
      'Regional shortages can increase latency.',
    ),
    n(
      'server',
      'realtime',
      'Authoritative Game Server',
      'compute',
      3,
      'Validates inputs and advances the simulation on ticks.',
      'Clients cannot be trusted to declare outcomes.',
      'Tick deadlines constrain computation.',
      'HOT PATH',
    ),
    n(
      'guard',
      'auth',
      'Input Validation / Anti-cheat',
      'security',
      4,
      'Rejects invalid actions inside the server’s simulation boundary.',
      'Client prediction is not authoritative.',
      'Validation costs part of the tick budget.',
    ),
    n(
      'database',
      'database',
      'Match Results / Inventory',
      'data',
      4,
      'Persists durable outcomes after the match.',
      'Player progression should survive session shutdown.',
      'Cross-service rewards require deduplication.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'leaderboard',
      'search',
      'Leaderboards',
      'data',
      5,
      'Projects completed results into ranked views.',
      'Ranked queries differ from transactional result storage.',
      'Leaderboards can lag committed results.',
    ),
  ],
  scenarios: [
    flow(
      'join-match',
      'Join Match',
      'Use a control path to allocate a regional authoritative session.',
      'Matchmaking uses APIs; real-time gameplay connects directly to the session server.',
      [
        s(
          'client',
          'gateway',
          'Join matchmaking queue',
          'Authenticate and submit region and match preferences.',
          'Queue admission needs identity and eligibility.',
          'Unauthorized sessions.',
        ),
        s(
          'gateway',
          'service',
          'Form a match',
          'Group compatible players within a waiting budget.',
          'Fairness and queue time must be balanced.',
          'Unbounded waiting.',
        ),
        s(
          'service',
          'allocator',
          'Reserve regional capacity',
          'Choose a server with simulation capacity.',
          'An overloaded server misses tick deadlines.',
          'Poor gameplay responsiveness.',
        ),
        s(
          'allocator',
          'server',
          'Create authoritative session',
          'Initialize the match and validate its join tokens.',
          'Session ownership must be explicit.',
          'Players joining the wrong match.',
        ),
        s(
          'allocator',
          'client',
          'Return session endpoint',
          'Give the client a scoped join token and endpoint.',
          'The gateway should not proxy gameplay packets.',
          'API latency in the tick loop.',
          'ack',
        ),
        s(
          'client',
          'server',
          'Connect to game transport',
          'Start the session’s real-time protocol directly.',
          'Gameplay has tighter latency needs than ordinary API calls.',
          'REST-shaped gameplay bottlenecks.',
        ),
      ],
    ),
    flow(
      'movement',
      'Player Movement',
      'Predict locally, validate on the server, and reconcile authoritative state.',
      'Clients send input intent; the server decides the resulting world state.',
      [
        s(
          'client',
          'server',
          'Send sequenced input',
          'Send movement intent while predicting locally.',
          'Waiting for each round trip would feel sluggish.',
          'Input lag.',
        ),
        s(
          'server',
          'guard',
          'Validate the action',
          'Check movement bounds and session rules within the tick.',
          'Client-reported positions can be manipulated.',
          'Impossible movement.',
        ),
        s(
          'guard',
          'server',
          'Advance authoritative tick',
          'Apply valid input to the server simulation.',
          'One authority resolves conflicting interactions.',
          'Divergent world outcomes.',
          'ack',
        ),
        s(
          'server',
          'client',
          'Reconcile local prediction',
          'Send authoritative state and acknowledged input sequence.',
          'The client replays unacknowledged inputs after correction.',
          'Persistent prediction drift.',
          'replication',
          { parallelGroup: 'state-replication' },
        ),
        s(
          'server',
          'peer',
          'Replicate to nearby player',
          'Send relevant state for interpolation.',
          'Interest management bounds bandwidth.',
          'Broadcasting the entire world.',
          'replication',
          { parallelGroup: 'state-replication' },
        ),
        s(
          'server',
          'client',
          'Recover a delayed snapshot',
          'A later snapshot supersedes an older lost update; interpolate and reconcile.',
          'Real-time state can favor newer data over retransmitting stale state.',
          'Accumulating latency.',
          'replication',
          { condition: 'network-degraded' },
        ),
      ],
      ['normal', 'network-degraded'],
    ),
    flow(
      'match-result',
      'Match Result',
      'Commit durable outcomes separately from the live tick loop.',
      'A match result is durable business state, not another ephemeral snapshot.',
      [
        s(
          'server',
          'database',
          'Commit match result',
          'Persist the authoritative outcome with a unique match ID and outbox entry.',
          'Session servers are replaceable.',
          'Lost rewards.',
          'write',
        ),
        s(
          'database',
          'events',
          'Publish committed result',
          'Relay the result for downstream projections.',
          'Ranking updates need not extend the match lifetime.',
          'Coupled service availability.',
          'event',
        ),
        s(
          'events',
          'leaderboard',
          'Project rankings',
          'Apply each match outcome idempotently.',
          'Event delivery can repeat.',
          'Double-counted scores.',
          'event',
        ),
        s(
          'database',
          'client',
          'Confirm progression',
          'Return committed rewards and inventory changes.',
          'UI should distinguish provisional from saved progress.',
          'False reward confirmation.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'fortnite',
      name: 'Fortnite-style',
      summary:
        'A conceptual authoritative multiplayer architecture informed by Unreal Engine networking documentation. This does not describe Fortnite’s private service topology.',
      era: 'Unreal Engine public networking concepts; Fortnite topology conceptual',
      sources: [sources.epic],
      overrides: {
        'rw-server': {
          sourceIds: ['epic'],
          description:
            'Unreal Engine documents authoritative client/server networking. This session boundary is a teaching model, not a verified Fortnite deployment.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
