import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'music',
  nodes: [
    ...commonNodes(),
    n(
      'service',
      'services',
      'Playback Control',
      'compute',
      2,
      'Resolves track metadata and authorized playback locations.',
      'Keep playback decisions separate from audio delivery.',
      'Control availability still affects starting a song.',
    ),
    n(
      'rights',
      'auth',
      'Rights / Region',
      'security',
      3,
      'Checks market availability and playback entitlement.',
      'A catalog entry is not playable in every context.',
      'Rights changes need timely propagation.',
    ),
    n(
      'metadata',
      'database',
      'Track Metadata',
      'data',
      3,
      'Stores artists, albums, encodings, and track identifiers.',
      'Playlists should reference stable catalog entities.',
      'Catalog corrections need identity reconciliation.',
    ),
    n(
      'playlist',
      'services',
      'Playlist Service',
      'compute',
      2,
      'Maintains ordered lists and collaborative edits.',
      'Playlist state changes independently of audio bytes.',
      'Concurrent edits require conflict rules.',
    ),
    n(
      'cdn',
      'cdn',
      'Audio CDN',
      'network',
      1,
      'Delivers encoded audio directly to listeners.',
      'Audio bandwidth should bypass control services.',
      'Cold content requires origin access.',
      'HOT PATH',
    ),
    n(
      'storage',
      'storage',
      'Encoded Audio Origin',
      'data',
      4,
      'Stores durable encoded representations.',
      'Edges can cache selectively while origin retains the catalog.',
      'Storage and encoding costs grow with formats.',
    ),
    n(
      'recommend',
      'ranking',
      'Home Recommendations',
      'compute',
      4,
      'Ranks personalized content from listening signals.',
      'A large catalog needs useful discovery.',
      'Feedback loops can narrow recommendations.',
    ),
    n(
      'signals',
      'database',
      'Listening Signals',
      'data',
      3,
      'Aggregates interaction history for personalization.',
      'Signals should not block playback.',
      'Retention and consent constrain usage.',
    ),
  ],
  scenarios: [
    flow(
      'play-song',
      'Play Song',
      'Check rights and metadata, then deliver audio on a separate media path.',
      'Playback control is small; the CDN carries the audio.',
      [
        s(
          'client',
          'gateway',
          'Request track playback',
          'Send the selected track and listening context.',
          'Authorization is needed before choosing delivery URLs.',
          'Uncontrolled playback.',
        ),
        s(
          'gateway',
          'service',
          'Create playback context',
          'Route to the playback owner.',
          'Catalog and entitlement checks share context.',
          'Inconsistent playback decisions.',
        ),
        s(
          'service',
          'rights',
          'Check regional rights',
          'Validate the listener’s playback eligibility.',
          'Availability differs by market and entitlement.',
          'Unavailable content.',
          'read',
          { parallelGroup: 'song-prepare' },
        ),
        s(
          'service',
          'metadata',
          'Resolve track encodings',
          'Fetch prepared audio representations.',
          'Metadata reads can overlap rights checks.',
          'Serial startup latency.',
          'read',
          { parallelGroup: 'song-prepare' },
        ),
        s(
          'service',
          'client',
          'Return authorized audio URL',
          'Join successful checks and return delivery information.',
          'Control responses should not contain the audio payload.',
          'Service bandwidth load.',
          'ack',
        ),
        s(
          'client',
          'cdn',
          'Request audio bytes',
          'Fetch encoded audio directly from the edge.',
          'Edge delivery reduces distance to the listener.',
          'Slow playback startup.',
          'media',
        ),
        s(
          'cdn',
          'storage',
          'Fill a cold audio object',
          'Retrieve missing encoded bytes from origin.',
          'The CDN is a cache.',
          'Missing unpopular tracks.',
          'cache-miss',
          { excludeWhen: ['cache-hit'] },
        ),
        s(
          'storage',
          'cdn',
          'Fill the edge',
          'Cache the requested representation.',
          'Future requests can reuse it.',
          'Repeated origin transfer.',
          'media',
          { excludeWhen: ['cache-hit'] },
        ),
        s(
          'cdn',
          'client',
          'Stream audio',
          'Deliver bytes while the player manages its buffer.',
          'Playback proceeds independently of the control path.',
          'Centralized delivery bottlenecks.',
          'media',
        ),
        s(
          'client',
          'events',
          'Publish listening signal',
          'Send playback events asynchronously.',
          'Analytics must not stall the song.',
          'Coupled user latency.',
          'telemetry',
        ),
      ],
      ['normal', 'cache-hit', 'cache-miss'],
    ),
    flow(
      'playlist',
      'Load Playlist',
      'Hydrate an ordered list without conflating it with media delivery.',
      'A playlist contains references, not copies of audio.',
      [
        s(
          'client',
          'playlist',
          'Read playlist revision',
          'Request ordered track IDs and the playlist version.',
          'Concurrent edits need a consistent revision.',
          'Inconsistent list ordering.',
          'read',
        ),
        s(
          'playlist',
          'metadata',
          'Hydrate track references',
          'Resolve names and current catalog state.',
          'A track can become unavailable independently of the playlist.',
          'Broken references.',
          'read',
        ),
        s(
          'metadata',
          'client',
          'Render playlist',
          'Return display metadata; playback rights are checked when playing.',
          'Browsing a list is not authorization to stream.',
          'Confusing metadata with media access.',
          'ack',
        ),
      ],
    ),
    flow(
      'recommendations',
      'Generate Recommendations',
      'Use asynchronous listening signals to personalize the next visit.',
      'The feedback pipeline improves discovery without blocking playback.',
      [
        s(
          'events',
          'signals',
          'Aggregate listening history',
          'Deduplicate and aggregate permitted events.',
          'Raw events can repeat and arrive late.',
          'Biased counts.',
          'event',
        ),
        s(
          'signals',
          'recommend',
          'Build recommendation features',
          'Create candidate and ranking inputs.',
          'Serving should not scan raw history for every request.',
          'High recommendation latency.',
          'read',
        ),
        s(
          'client',
          'recommend',
          'Request Home recommendations',
          'Rank candidates for the current context.',
          'Listening habits alone do not capture the current intent.',
          'Irrelevant discovery.',
        ),
        s(
          'recommend',
          'client',
          'Return discovery rows',
          'Present a ranked collection of tracks and playlists.',
          'A large catalog needs a manageable entry point.',
          'Choice overload.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'spotify',
      name: 'Spotify-style',
      summary:
        'A conceptual audio-delivery system with a publicly documented Home personalization component.',
      era: 'Home personalization evidence: 2020',
      sources: [sources.spotify],
      overrides: {
        'rw-recommend': {
          confidence: 'verified',
          sourceIds: ['spotify'],
          description:
            'Spotify documented machine-learning personalization of Home using listening and interaction signals in 2020. The surrounding service topology is conceptual.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
