import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'payments',
  nodes: [
    ...commonNodes(),
    n(
      'idempotency',
      'database',
      'Idempotency Boundary',
      'data',
      2,
      'Associates a request key with its parameters and recorded result.',
      'Retries must resolve one logical operation.',
      'A key is scoped and has a retention policy.',
      'CONSISTENCY BOUNDARY',
    ),
    n(
      'service',
      'services',
      'Payment Intent',
      'compute',
      2,
      'Tracks the lifecycle of an attempted payment.',
      'Creation, authorization, and capture are different states.',
      'Asynchronous outcomes require a state machine.',
    ),
    n(
      'risk',
      'auth',
      'Risk Checks',
      'security',
      3,
      'Evaluates a payment before proceeding to the processor.',
      'Suspicious activity should be intercepted early.',
      'False positives reject legitimate customers.',
    ),
    n(
      'processor',
      'services',
      'Processor / Network',
      'network',
      3,
      'Coordinates external authorization, capture, and refund requests.',
      'External financial systems have their own outcomes.',
      'A timeout leaves status uncertain.',
    ),
    n(
      'ledger',
      'database',
      'Double-entry Ledger',
      'data',
      4,
      'Records balanced durable financial movements and references.',
      'Money changes need an auditable history.',
      'Corrections use new entries, not silent edits.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'webhook',
      'notifications',
      'Webhook Delivery',
      'events',
      5,
      'Retries signed event notifications to merchants.',
      'The browser may disconnect before the final outcome.',
      'Receivers must deduplicate and verify authenticity.',
    ),
    n(
      'settlement',
      'workers',
      'Settlement / Reconciliation',
      'compute',
      4,
      'Compares processor reports with internal records and tracks transferred funds.',
      'Captured and settled are different milestones.',
      'Reconciliation can discover delayed discrepancies.',
    ),
  ],
  scenarios: [
    flow(
      'make-payment',
      'Make Payment',
      'Authorize an intent while deduplicating retries and handling uncertain external outcomes.',
      'Idempotency gives one logical effect; it does not make the network deliver exactly once.',
      [
        s(
          'client',
          'gateway',
          'Submit payment key',
          'Send payment parameters with a stable idempotency key.',
          'A lost response often causes a client retry.',
          'Duplicate financial operations.',
        ),
        s(
          'gateway',
          'idempotency',
          'Claim or replay the key',
          'Validate matching parameters and resolve an existing result or begin one operation.',
          'The same key cannot safely mean two different requests.',
          'Duplicate or conflicting effects.',
          'write',
        ),
        s(
          'idempotency',
          'service',
          'Create payment intent',
          'Track an explicit payment lifecycle.',
          'An API acknowledgment is not settlement.',
          'Ambiguous payment state.',
        ),
        s(
          'service',
          'risk',
          'Evaluate the attempt',
          'Check risk signals before external authorization.',
          'Reject unsafe attempts before moving further.',
          'Avoidable financial exposure.',
        ),
        s(
          'risk',
          'processor',
          'Request authorization',
          'Ask the network to authorize a hold, not settle funds.',
          'Authorization checks availability without final capture.',
          'Conflating payment stages.',
        ),
        s(
          'processor',
          'service',
          'Authorization accepted',
          'Record an authorized state for later capture.',
          'Funds held are not yet captured or settled.',
          'False settled status.',
          'ack',
          { excludeWhen: ['payment-timeout'] },
        ),
        s(
          'processor',
          'service',
          'Authorization reply missing',
          'Keep the intent pending when the processor times out.',
          'Timeout does not establish success or failure.',
          'Unsafe duplicate authorization.',
          'ack',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'processor',
          'Resolve the same attempt',
          'Query or retry under the processor’s deduplication contract.',
          'Reconcile uncertainty before starting another attempt.',
          'Duplicate holds.',
          'request',
          { condition: 'payment-timeout' },
        ),
        s(
          'processor',
          'service',
          'Recover authorization result',
          'In this branch the original attempt was authorized.',
          'The recovered outcome belongs to the original intent.',
          'Mismatched records.',
          'ack',
          { condition: 'payment-timeout' },
        ),
        s(
          'service',
          'idempotency',
          'Save stable operation result',
          'Record the response and reference for safe replay.',
          'A client retry should resolve this operation.',
          'Repeated business effects.',
          'write',
        ),
        s(
          'service',
          'client',
          'Return authorization status',
          'Return the persisted authorized intent and its stable operation reference.',
          'The client can display authorization only after receiving the result.',
          'Confusing an internal processor outcome with client confirmation.',
          'ack',
        ),
        s(
          'service',
          'events',
          'Publish intent state',
          'Publish the durable status transition via an outbox.',
          'Merchants may need asynchronous confirmation.',
          'Dependence on the browser connection.',
          'event',
        ),
        s(
          'events',
          'webhook',
          'Notify merchant',
          'Deliver a signed status event with retries.',
          'The receiver can be temporarily unavailable.',
          'Lost notifications.',
          'event',
        ),
      ],
      ['normal', 'payment-timeout'],
    ),
    flow(
      'capture',
      'Capture Payment',
      'Capture an existing authorization and record the financial effect.',
      'Capture and settlement are distinct; a successful capture does not mean funds have arrived.',
      [
        s(
          'client',
          'service',
          'Capture authorized intent',
          'Reference the authorized payment and a stable capture key.',
          'Capture must not create a new authorization.',
          'Duplicate payment attempts.',
        ),
        s(
          'service',
          'processor',
          'Submit capture',
          'Capture the allowed amount against the authorization.',
          'Authorization may expire or be partially capturable.',
          'Invalid financial transitions.',
        ),
        s(
          'processor',
          'ledger',
          'Record confirmed capture',
          'After confirmation, append balanced entries with processor references.',
          'Every movement needs an auditable counterpart.',
          'Unbalanced internal accounts.',
          'write',
        ),
        s(
          'ledger',
          'events',
          'Publish capture committed',
          'Relay the committed capture record.',
          'Delivery may repeat without repeating the ledger effect.',
          'Double booking.',
          'event',
        ),
        s(
          'events',
          'webhook',
          'Notify capture result',
          'Tell the merchant the captured status.',
          'Fulfillment decisions should use a verified payment state.',
          'Premature fulfillment.',
          'event',
        ),
      ],
    ),
    flow(
      'refund',
      'Refund Payment',
      'Create a new compensating financial operation for a captured payment.',
      'A refund adds an auditable movement; it does not erase history.',
      [
        s(
          'client',
          'service',
          'Request refund',
          'Reference the captured payment and a stable refund key.',
          'Multiple refunds must remain within the refundable amount.',
          'Over-refunding.',
        ),
        s(
          'service',
          'processor',
          'Submit refund attempt',
          'Send the deduplicated refund operation to the processor.',
          'Refund completion may be asynchronous.',
          'Duplicate refunds.',
        ),
        s(
          'processor',
          'ledger',
          'Record confirmed refund',
          'Append balanced reversing movements after confirmation.',
          'Historical capture entries remain intact.',
          'Unauditable deletion of history.',
          'write',
        ),
        s(
          'ledger',
          'events',
          'Publish refund status',
          'Relay the committed financial state.',
          'Merchants and customers need a consistent reference.',
          'Status divergence.',
          'event',
        ),
        s(
          'events',
          'webhook',
          'Deliver refund event',
          'Retry delivery with a stable event identifier.',
          'Merchant endpoints can fail.',
          'Lost refund notification.',
          'event',
        ),
      ],
    ),
    flow(
      'reconcile',
      'Reconcile Transaction',
      'Compare processor settlement records with the internal ledger.',
      'Authorization, capture, and actual funds settlement are separate milestones.',
      [
        s(
          'processor',
          'settlement',
          'Receive settlement report',
          'Ingest externally reported transfers and fees.',
          'Internal API success is not evidence of bank settlement.',
          'Unverified cash position.',
          'event',
        ),
        s(
          'settlement',
          'ledger',
          'Match financial references',
          'Compare amounts and references against expected ledger movements.',
          'External and internal systems can diverge.',
          'Unnoticed discrepancies.',
          'read',
        ),
        s(
          'ledger',
          'settlement',
          'Return matched and unmatched entries',
          'Classify discrepancies for investigation.',
          'Timing differences must not be silently written off.',
          'Hidden financial loss.',
          'ack',
        ),
        s(
          'settlement',
          'ledger',
          'Record resolved settlement',
          'Append balanced settlement or adjustment entries with an audit trail.',
          'Corrections must preserve history.',
          'Untraceable reconciliation.',
          'write',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'stripe',
      name: 'Stripe-style',
      summary:
        'Stripe’s public idempotency and PaymentIntent behavior, surrounded by conceptual risk, ledger, processor, and settlement boundaries.',
      era: 'Public API documentation; internal topology conceptual',
      sources: [sources.stripe, sources.intents],
      overrides: {
        'rw-idempotency': {
          confidence: 'verified',
          sourceIds: ['stripe'],
          description:
            'Stripe documents replaying a recorded response for matching idempotent API requests. This box describes that public contract, not a confirmed internal database.',
        },
        'rw-service': {
          label: 'PaymentIntent API',
          confidence: 'verified',
          sourceIds: ['intents'],
          description:
            'Stripe documents PaymentIntent state transitions. The service boundaries surrounding this public abstraction are conceptual.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
