import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'ride',
  nodes: [
    ...commonNodes(),
    n(
      'driver',
      'client',
      'Driver App',
      'client',
      0,
      'Reports location and accepts dispatch offers.',
      'Driver movement is independent of rider requests.',
      'Connectivity and GPS accuracy vary.',
    ),
    n(
      'ingest',
      'realtime',
      'Location Ingestion',
      'network',
      1,
      'Validates and timestamps frequent driver updates.',
      'Do not send every coordinate through the trip transaction.',
      'Late updates must not replace newer positions.',
    ),
    n(
      'geo',
      'cache',
      'Live Location Index',
      'data',
      3,
      'Finds nearby available drivers using fresh expiring positions.',
      'Bound candidate discovery geographically.',
      'A nearby result may already be stale.',
      'HOT PATH',
    ),
    n(
      'service',
      'services',
      'Ride / Dispatch',
      'compute',
      2,
      'Owns the ride request and dispatch attempts.',
      'Separate durable trip state from rapidly changing location.',
      'Concurrent requests may compete for a driver.',
    ),
    n(
      'match',
      'services',
      'Matching & ETA',
      'compute',
      3,
      'Scores candidates using pickup time and availability.',
      'Nearest by straight-line distance may not arrive fastest.',
      'ETA computation adds latency.',
    ),
    n(
      'price',
      'services',
      'Marketplace Analysis',
      'compute',
      4,
      'Aggregates geographic demand and supply for pricing analysis.',
      'Local market conditions differ across a city.',
      'Aggregation smooths detail and lags changes.',
    ),
    n(
      'database',
      'database',
      'Trip State',
      'data',
      4,
      'Atomically records assignment and trip transitions.',
      'One driver must not accept incompatible active trips.',
      'Strong assignment consistency can reduce availability.',
      'CONSISTENCY BOUNDARY',
    ),
    n(
      'payment',
      'services',
      'Trip Payment',
      'compute',
      5,
      'Settles a completed trip using a stable trip payment ID.',
      'Completion events can be retried.',
      'Processor outcomes can be temporarily uncertain.',
    ),
  ],
  scenarios: [
    flow(
      'request-ride',
      'Request Ride',
      'Discover moving drivers, select a candidate, and commit an exclusive assignment.',
      'The location index suggests candidates; the assignment transaction decides ownership.',
      [
        s(
          'client',
          'gateway',
          'Request a ride',
          'Send pickup and destination with a request ID.',
          'Retries should refer to the same ride request.',
          'Duplicate bookings.',
          'request',
          { parallelGroup: 'ride-start' },
        ),
        s(
          'driver',
          'ingest',
          'Send timestamped GPS',
          'Sample driver positions while the rider request begins independently.',
          'Location ingestion must remain separate from the booking transaction.',
          'Stale candidate positions.',
          'request',
          { parallelGroup: 'ride-start' },
        ),
        s(
          'gateway',
          'service',
          'Open dispatch request',
          'Create a pending ride with a dispatch deadline.',
          'Unbounded matching leaves riders waiting indefinitely.',
          'Unclear request state.',
          'request',
          { parallelGroup: 'dispatch-location' },
        ),
        s(
          'ingest',
          'geo',
          'Refresh live position',
          'Apply newer observations and expire stale driver positions.',
          'Matching reads fresh candidates while dispatch creates its pending request.',
          'Out-of-order coordinates.',
          'write',
          { parallelGroup: 'dispatch-location' },
        ),
        s(
          'service',
          'geo',
          'Find nearby drivers',
          'Read recent positions and availability hints.',
          'Search a bounded area before expensive scoring.',
          'Scanning the fleet.',
          'read',
        ),
        s(
          'geo',
          'match',
          'Score candidates',
          'Estimate road travel time and reject stale candidates.',
          'Distance alone is not pickup time.',
          'Poor matches.',
        ),
        s(
          'match',
          'driver',
          'Offer the ride',
          'Send a time-limited offer to a candidate.',
          'The driver may decline or disconnect.',
          'Assuming availability implies acceptance.',
        ),
        s(
          'driver',
          'service',
          'Accept the offer',
          'Return the offer token before its deadline.',
          'An old offer must not win a newer dispatch attempt.',
          'Late acceptance races.',
          'ack',
        ),
        s(
          'service',
          'database',
          'Commit assignment',
          'Use a conditional state transition to reserve the driver.',
          'Two rides may race for the same person.',
          'Double assignment.',
          'write',
        ),
        s(
          'database',
          'client',
          'Confirm pickup',
          'Only after the assignment commits, show driver details.',
          'A provisional match is not a confirmed ride.',
          'False confirmation.',
          'ack',
        ),
      ],
    ),
    flow(
      'location-update',
      'Driver Location Update',
      'Update high-frequency positions outside the booking transaction.',
      'Location freshness and trip consistency need different storage paths.',
      [
        s(
          'driver',
          'ingest',
          'Send timestamped GPS',
          'Batch or sample location updates from the moving driver.',
          'Battery and bandwidth are limited.',
          'Excess device traffic.',
        ),
        s(
          'ingest',
          'geo',
          'Refresh live position',
          'Apply only newer observations and expire stale entries.',
          'Delayed packets can arrive out of order.',
          'Moving a driver backward in time.',
          'write',
        ),
        s(
          'ingest',
          'events',
          'Publish location signal',
          'Retain a sampled event for downstream processing.',
          'Analytics should not delay live driver discovery.',
          'Coupled latency.',
          'event',
        ),
        s(
          'events',
          'price',
          'Aggregate marketplace cells',
          'Roll up demand and supply geographically.',
          'Pricing analysis needs a spatial summary.',
          'Unbounded raw-coordinate queries.',
          'event',
          { parallelGroup: 'location-consumers' },
        ),
        s(
          'events',
          'client',
          'Update rider map',
          'Deliver relevant trip movement to the subscribed rider.',
          'Riders need progress without polling all drivers.',
          'Polling load.',
          'event',
          { parallelGroup: 'location-consumers' },
        ),
      ],
    ),
    flow(
      'complete-trip',
      'Complete Trip',
      'Commit trip completion and collect payment asynchronously.',
      'The trip can be complete while payment processing is still pending.',
      [
        s(
          'driver',
          'service',
          'End the trip',
          'Submit the final trip state with a stable ID.',
          'Mobile retries are expected.',
          'Duplicate trip completion.',
        ),
        s(
          'service',
          'database',
          'Commit fare and completion',
          'Persist the final fare and outbox event.',
          'Billing must correspond to committed trip facts.',
          'Mismatched trip and charge.',
          'write',
        ),
        s(
          'database',
          'events',
          'Relay completed trip',
          'Publish the durable completion event.',
          'Consumers can recover after outages.',
          'Lost billing work.',
          'event',
        ),
        s(
          'events',
          'payment',
          'Collect fare',
          'Use the trip ID to deduplicate processor requests.',
          'Event delivery can repeat.',
          'Duplicate charges.',
          'event',
        ),
        s(
          'payment',
          'client',
          'Send payment status',
          'Report the actual processor outcome.',
          'Pending and paid are different states.',
          'Misleading receipts.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'uber',
      name: 'Uber',
      summary:
        'A conceptual dispatch and live-location model, with H3 grounded in Uber’s published marketplace analysis work.',
      era: 'H3 evidence: 2018; live dispatch reconstruction',
      sources: [sources.uber],
      overrides: {
        'rw-price': {
          label: 'H3 Marketplace Analysis',
          technology: 'H3',
          confidence: 'verified',
          sourceIds: ['uber'],
          description:
            'Uber documented H3 for marketplace analysis, pricing, and dispatch optimization. This does not establish the live driver-store implementation.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
