import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'search',
  nodes: [
    ...commonNodes().filter((n) => n.id !== 'rw-events'),
    n(
      'web',
      'client',
      'Public Web',
      'client',
      0,
      'Provides pages for permitted crawling.',
      'Search needs content before a query arrives.',
      'Sites can change or block access.',
    ),
    n(
      'crawler',
      'workers',
      'Crawler / URL Frontier',
      'compute',
      1,
      'Schedules permitted URL fetches with politeness limits.',
      'Avoid overwhelming origin websites.',
      'Freshness competes with crawl budget.',
    ),
    n(
      'indexer',
      'workers',
      'Parse / Deduplicate / Index',
      'compute',
      2,
      'Extracts content, canonicalizes duplicates, and builds index updates.',
      'Queries should not parse the live web.',
      'Index changes take time to publish.',
    ),
    n(
      'service',
      'services',
      'Query Coordinator',
      'compute',
      2,
      'Parses the query and fans it out to index partitions.',
      'Relevant documents span many partitions.',
      'Tail latency from a slow shard can dominate.',
      'HOT PATH',
    ),
    n(
      'shard-a',
      'search',
      'Index Shard A',
      'data',
      3,
      'Searches one partition of the inverted index.',
      'Partition the corpus to bound local work.',
      'Global scoring needs comparable shard statistics.',
    ),
    n(
      'shard-b',
      'search',
      'Index Shard B',
      'data',
      3,
      'Searches another partition concurrently.',
      'Parallel shard work reduces serial query time.',
      'A missing shard can reduce recall.',
    ),
    n(
      'rank',
      'ranking',
      'Merge & Rank',
      'compute',
      4,
      'Combines shard candidates and applies final relevance ordering.',
      'Local top results must become one global page.',
      'Ranking costs grow with candidate count.',
    ),
    n(
      'cache',
      'cache',
      'Query Cache',
      'data',
      3,
      'Caches reusable query results with freshness limits.',
      'Popular queries repeat.',
      'Personalization limits safe cache reuse.',
    ),
    n(
      'suggest',
      'search',
      'Autocomplete Index',
      'data',
      2,
      'Returns prefix suggestions from a dedicated read path.',
      'Typing latency budgets are shorter than full search.',
      'Suggestions need abuse and privacy filtering.',
    ),
  ],
  scenarios: [
    flow(
      'search-query',
      'Search Query',
      'Fan a parsed query across independent index partitions.',
      'Parallel shard search is followed by a merge barrier and global ranking.',
      [
        s(
          'client',
          'gateway',
          'Submit query',
          'Send search terms and context.',
          'Queries need normalization before dispatch.',
          'Inconsistent interpretation.',
        ),
        s(
          'gateway',
          'service',
          'Parse and plan',
          'Normalize spelling and determine eligible partitions.',
          'Avoid unnecessary shard work.',
          'Query fanout cost.',
        ),
        s(
          'service',
          'cache',
          'Look for reusable results',
          'Check the query and context cache key.',
          'Popular queries can bypass repeated ranking.',
          'Backend load.',
          'read',
        ),
        s(
          'cache',
          'client',
          'Return cached results',
          'A valid cached page skips shard work.',
          'Reuse is safe only within the freshness and context policy.',
          'Repeated computation.',
          'cache-hit',
          { condition: 'cache-hit' },
        ),
        s(
          'service',
          'shard-a',
          'Search partition A',
          'Retrieve local candidates using the inverted index.',
          'The corpus is partitioned.',
          'Single-machine limits.',
          'read',
          { parallelGroup: 'shards', excludeWhen: ['cache-hit'] },
        ),
        s(
          'service',
          'shard-b',
          'Search partition B',
          'Search the second partition at the same time.',
          'Independent partitions can work concurrently.',
          'Serial fanout latency.',
          'read',
          { parallelGroup: 'shards', excludeWhen: ['cache-hit'] },
        ),
        s(
          'shard-a',
          'rank',
          'Merge candidates A',
          'Return local top candidates to the merge barrier.',
          'Final ranking requires cross-shard candidates.',
          'Biased local ordering.',
          'ack',
          { parallelGroup: 'merge', excludeWhen: ['cache-hit'] },
        ),
        s(
          'shard-b',
          'rank',
          'Merge candidates B',
          'Complete the other side of the merge barrier.',
          'The coordinator waits within a bounded deadline.',
          'Unbounded tail latency.',
          'ack',
          { parallelGroup: 'merge', excludeWhen: ['cache-hit'] },
        ),
        s(
          'rank',
          'client',
          'Return ranked results',
          'Render the merged top results with snippets.',
          'The user needs one ordered page.',
          'Fragmented shard responses.',
          'ack',
          { excludeWhen: ['cache-hit'] },
        ),
      ],
      ['normal', 'cache-hit', 'cache-miss'],
    ),
    flow(
      'crawl-index',
      'Crawl & Index',
      'Prepare searchable content independently of online queries.',
      'Crawling and indexing are an offline pipeline; serving reads published indexes.',
      [
        s(
          'crawler',
          'web',
          'Fetch permitted page',
          'Choose a URL from the frontier and respect crawl policy.',
          'Origin servers have finite capacity.',
          'Aggressive crawling.',
        ),
        s(
          'web',
          'indexer',
          'Parse and deduplicate',
          'Extract text and canonicalize equivalent documents.',
          'Repeated pages should not inflate the index.',
          'Duplicate results.',
          'write',
        ),
        s(
          'indexer',
          'shard-a',
          'Publish partition A',
          'Build and publish an index generation for partition A.',
          'Readers need a consistent searchable generation.',
          'Half-published index state.',
          'write',
          { parallelGroup: 'publish-index' },
        ),
        s(
          'indexer',
          'shard-b',
          'Publish partition B',
          'Publish the corresponding update for partition B.',
          'Indexing can partition work across workers.',
          'Single-worker throughput.',
          'write',
          { parallelGroup: 'publish-index' },
        ),
      ],
    ),
    flow(
      'autocomplete',
      'Autocomplete',
      'Serve suggestions without running a full corpus search on every keystroke.',
      'A dedicated prefix path protects the full-query budget.',
      [
        s(
          'client',
          'suggest',
          'Submit debounced prefix',
          'Send a prefix after a short typing pause.',
          'Every keypress need not trigger network work.',
          'Request amplification.',
        ),
        s(
          'suggest',
          'client',
          'Return safe suggestions',
          'Rank prefix completions and apply safety filters.',
          'Suggestions are not guaranteed search results.',
          'Slow or inappropriate completions.',
          'ack',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'google',
      name: 'Google-style Search',
      summary:
        'Google’s documented crawl/index/serve stages, with illustrative physical shards and query coordination.',
      era: 'Public Search Central documentation; physical topology conceptual',
      sources: [sources.google],
      overrides: {
        'rw-crawler': {
          confidence: 'verified',
          sourceIds: ['google'],
          description:
            'Google documents crawling as a stage of Search. The frontier’s precise implementation is not asserted.',
        },
        'rw-indexer': {
          confidence: 'verified',
          sourceIds: ['google'],
          description:
            'Google documents indexing and canonicalization. The physical partition design shown here is conceptual.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
