import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
const miss = { excludeWhen: ['cache-hit'] as const };
export default {
  familyId: 'social',
  nodes: [
    ...commonNodes(),
    n(
      'service',
      'services',
      'Feed Service',
      'compute',
      2,
      'Builds cursor-based pages of feed candidates.',
      'Keep pagination stable as new posts arrive.',
      'Freshness competes with ranking cost.',
      'HOT PATH',
    ),
    n(
      'cache',
      'cache',
      'Timeline Cache',
      'data',
      3,
      'Stores precomputed candidate IDs, not the authoritative posts.',
      'Avoid rebuilding each timeline on every read.',
      'Invalidation and hot accounts complicate caching.',
      'BOTTLENECK RISK',
    ),
    n(
      'graph',
      'graph-database',
      'Social Graph',
      'data',
      3,
      'Resolves follows and visibility relationships.',
      'Find eligible authors before ranking.',
      'Large adjacency lists need partitioning.',
    ),
    n(
      'rank',
      'ranking',
      'Ranking',
      'compute',
      4,
      'Scores candidates for the viewer and context.',
      'Select useful posts from a much larger candidate set.',
      'Model cost and freshness must fit a latency budget.',
    ),
    n(
      'posts',
      'database',
      'Post Store',
      'data',
      4,
      'Persists post records and visibility state.',
      'Hydrate candidate IDs from durable records.',
      'Deleted posts must disappear from cached timelines.',
      'DURABILITY BOUNDARY',
    ),
    n(
      'write',
      'services',
      'Post Service',
      'compute',
      2,
      'Validates and commits a post with an outbox event.',
      'Publish only events corresponding to durable posts.',
      'Moderation can delay distribution.',
    ),
    n(
      'fanout',
      'workers',
      'Hybrid Fanout',
      'compute',
      5,
      'Pushes ordinary posts to follower timelines; keeps celebrity posts for read-time merge.',
      'Bound write amplification for very large audiences.',
      'Read-time merge increases feed latency.',
    ),
    n(
      'storage',
      'storage',
      'Media Store',
      'data',
      4,
      'Stores uploaded images separately from post metadata.',
      'Keep large bytes out of the transactional database.',
      'Orphaned uploads need cleanup.',
    ),
    n(
      'cdn',
      'cdn',
      'Media CDN',
      'network',
      1,
      'Serves authorized media URLs directly to clients.',
      'Avoid routing media bytes through feed services.',
      'Cache invalidation and access expiry must agree.',
    ),
    n(
      'notify',
      'notifications',
      'Notifications',
      'events',
      5,
      'Delivers notifications asynchronously.',
      'Do not block post creation on push providers.',
      'Delivery may be delayed or duplicated.',
    ),
  ],
  scenarios: [
    flow(
      'home-feed',
      'Load Home Feed',
      'Build a ranked page without scanning every post.',
      'Hybrid fanout trades cheap reads against bounded write amplification.',
      [
        s(
          'client',
          'gateway',
          'Request next page',
          'The client sends a cursor and viewer identity.',
          'A cursor avoids shifting offset pages.',
          'Stable pagination.',
        ),
        s(
          'gateway',
          'service',
          'Route the feed request',
          'The gateway passes authenticated identity to the feed owner.',
          'Authorization belongs to the viewer context.',
          'Cross-user data exposure.',
        ),
        s(
          'service',
          'cache',
          'Look up candidates',
          'Check for a precomputed timeline.',
          'Generating every feed from scratch is expensive.',
          'Read latency and database load.',
          'read',
        ),
        s(
          'cache',
          'service',
          'Cache hit',
          'Cached candidate IDs are available.',
          'Reuse work while still enforcing visibility.',
          'Repeated candidate generation.',
          'cache-hit',
          { condition: 'cache-hit' },
        ),
        s(
          'cache',
          'service',
          'Cache miss',
          'No usable timeline is present.',
          'A cache is disposable, not authoritative.',
          'Recovery after eviction.',
          'cache-miss',
          { excludeWhen: [...miss.excludeWhen] },
        ),
        s(
          'service',
          'graph',
          'Resolve followed authors',
          'Read follow relationships and merge celebrity candidates at read time.',
          'Celebrity posts should not trigger millions of synchronous writes.',
          'Unbounded fanout.',
          'read',
          { excludeWhen: [...miss.excludeWhen] },
        ),
        s(
          'graph',
          'service',
          'Return eligible candidates',
          'Return followed-author candidates for a cold timeline.',
          'The feed owner joins candidate sources.',
          'Disconnected candidate pipelines.',
          'ack',
          { excludeWhen: ['cache-hit'] },
        ),
        s(
          'service',
          'rank',
          'Rank eligible candidates',
          'Score candidates and filter visibility.',
          'A long candidate list must become a useful page.',
          'Relevance within a latency budget.',
        ),
        s(
          'rank',
          'posts',
          'Hydrate post records',
          'Fetch content for the ranked IDs and enforce deletions.',
          'Cached IDs are not the source of truth.',
          'Stale or inaccessible content.',
          'read',
        ),
        s(
          'posts',
          'service',
          'Slow hydration response',
          'The post store exceeds its usual latency budget; this branch returns a smaller partial page within a deadline.',
          'A slow dependency must not create unbounded waiting.',
          'Cascading request queues.',
          'ack',
          { condition: 'slow-database', duration: 6000 },
        ),
        s(
          'posts',
          'service',
          'Assemble the page',
          'Return post metadata, media URLs, and next cursor.',
          'Media bytes have their own delivery path.',
          'Oversized API responses.',
          'ack',
        ),
        s(
          'service',
          'cache',
          'Fill candidate cache',
          'Store reusable candidate IDs with a bounded freshness policy.',
          'The next read should not repeat candidate discovery.',
          'Repeated cold-path work.',
          'write',
          { excludeWhen: ['cache-hit', 'slow-database'] },
        ),
        s(
          'service',
          'client',
          'Return feed page',
          'Render the page immediately.',
          'Interaction must not wait for media downloads.',
          'Time to first useful content.',
          'ack',
        ),
        s(
          'client',
          'cdn',
          'Fetch media',
          'Load images directly from the CDN.',
          'Edge delivery is closer to the viewer.',
          'Bandwidth load on feed services.',
          'media',
        ),
      ],
      ['normal', 'cache-hit', 'cache-miss', 'slow-database'],
    ),
    flow(
      'create-post',
      'Create Post',
      'Commit the post before asynchronous distribution.',
      'An outbox connects durable state to retryable fanout.',
      [
        s(
          'client',
          'storage',
          'Upload media',
          'Upload the attachment before publishing its reference.',
          'Separate bulk transfer from the metadata transaction.',
          'Large request payloads.',
          'write',
        ),
        s(
          'client',
          'write',
          'Publish post',
          'Validate content and visibility.',
          'A post is not visible until validation succeeds.',
          'Invalid public content.',
        ),
        s(
          'write',
          'posts',
          'Commit post and outbox',
          'Persist the post and pending event atomically.',
          'The event must refer to a durable post.',
          'Lost or phantom events.',
          'write',
        ),
        s(
          'posts',
          'events',
          'Relay committed event',
          'An outbox relay publishes with retries.',
          'Database commit and broker publish are separate operations.',
          'Dual-write gaps.',
          'event',
          { parallelGroup: 'accept-and-relay' },
        ),
        s(
          'write',
          'client',
          'Post accepted',
          'The post is durable; downstream delivery can still be catching up.',
          'Acceptance does not promise immediate global visibility.',
          'Clear consistency expectations.',
          'ack',
          { parallelGroup: 'accept-and-relay' },
        ),
        s(
          'events',
          'fanout',
          'Update follower timelines',
          'Queue bounded batches of timeline updates.',
          'Large fanout should not hold open the API call.',
          'Write amplification.',
          'event',
          { parallelGroup: 'distribution' },
        ),
        s(
          'events',
          'notify',
          'Notify interested followers',
          'Notifications consume the same event independently.',
          'One slow consumer must not delay another.',
          'Coupled background work.',
          'event',
          { parallelGroup: 'distribution' },
        ),
        s(
          'fanout',
          'cache',
          'Populate timeline cache',
          'Deduplicate each post ID while updating timelines.',
          'At-least-once events can repeat.',
          'Duplicate feed entries.',
          'write',
        ),
      ],
    ),
    flow(
      'celebrity-post',
      'Celebrity Post',
      'Avoid a write to every follower timeline.',
      'A hybrid design shifts the largest fanouts to the read path.',
      [
        s(
          'client',
          'write',
          'Publish a high-fanout post',
          'The author has an exceptionally large follower set.',
          'Audience size changes the best distribution strategy.',
          'Extreme write amplification.',
        ),
        s(
          'write',
          'posts',
          'Persist once',
          'Commit the post and outbox record.',
          'Durability is independent of the fanout strategy.',
          'Lost content.',
          'write',
        ),
        s(
          'posts',
          'events',
          'Publish author update',
          'Relay the committed author event.',
          'Consumers classify distribution policy asynchronously.',
          'API latency.',
          'event',
        ),
        s(
          'events',
          'fanout',
          'Choose fanout on read',
          'Do not write this post into every follower cache.',
          'A single celebrity post can overwhelm fanout workers.',
          'Hot partitions.',
          'event',
        ),
        s(
          'service',
          'posts',
          'Merge on a follower read',
          'Read recent celebrity posts alongside cached ordinary candidates.',
          'The extra work is paid only by active readers.',
          'Unbounded background backlog.',
          'read',
        ),
        s(
          'posts',
          'rank',
          'Rank the merged set',
          'Apply the same ranking to both candidate sources.',
          'Distribution policy should not decide presentation order.',
          'Inconsistent feed ordering.',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'instagram',
      name: 'Instagram',
      summary:
        'A Home Feed teaching reconstruction informed by public Explore ranking work. Exact cache and fanout technologies are not publicly established here.',
      era: '2023 ranking evidence; broader flow inferred / conceptual',
      sources: [sources.instagram],
      overrides: {
        'rw-rank': {
          confidence: 'inferred',
          sourceIds: ['instagram'],
          description:
            'Multi-stage ranking is documented for Explore; its placement in this Home Feed model is an inference.',
        },
      },
    },
    {
      id: 'facebook',
      name: 'Facebook',
      summary: 'A feed reconstruction with a historical, documented TAO social-graph component.',
      era: 'TAO evidence: 2013; not a claim about today’s full stack',
      sources: [sources.facebook],
      overrides: {
        'rw-graph': {
          label: 'TAO Social Graph',
          technology: 'TAO (2013)',
          confidence: 'verified',
          sourceIds: ['facebook'],
          description:
            'Facebook documented TAO for social-graph access in 2013. This diagram’s full feed topology remains conceptual.',
        },
      },
    },
  ],
} satisfies FamilyBlueprint;
