import { commonNodes, node as n, scenario as flow, step as s } from '../builders';
import { sources } from '../sources';
import type { FamilyBlueprint } from '../types';
export default {
  familyId: 'video',
  nodes: [
    ...commonNodes(),
    n(
      'service',
      'services',
      'Playback Control',
      'compute',
      2,
      'Coordinates playback authorization and manifest selection.',
      'Keep small control messages separate from large media transfers.',
      'The control plane still needs high availability.',
    ),
    n(
      'rights',
      'auth',
      'Playback Authorization',
      'security',
      3,
      'Checks subscription and regional eligibility.',
      'A media URL must reflect permitted playback.',
      'Expired authorization can interrupt playback.',
    ),
    n(
      'metadata',
      'database',
      'Video Metadata',
      'data',
      3,
      'Provides title, duration, and available representations.',
      'The player needs a compact description before fetching bytes.',
      'Metadata and prepared media must agree.',
    ),
    n(
      'manifest',
      'services',
      'Manifest Service',
      'compute',
      4,
      'Returns representations and authorized segment locations.',
      'Let the player select bitrate and seek by time.',
      'Manifest freshness and URL lifetime must agree.',
    ),
    n(
      'cdn',
      'cdn',
      'Media Edge CDN',
      'network',
      1,
      'Serves encoded segments directly to players.',
      'Media bandwidth should bypass the API gateway.',
      'Cold titles need origin retrieval.',
      'HOT PATH',
    ),
    n(
      'storage',
      'storage',
      'Encoded Media Origin',
      'data',
      4,
      'Durably stores encoded segments for edge fill.',
      'Edges can evict content without losing the source.',
      'Origin bursts need shielding.',
    ),
    n(
      'upload',
      'storage',
      'Upload Staging',
      'data',
      2,
      'Receives source video before processing.',
      'Large uploads need resumable transfer and checksums.',
      'Uploaded does not mean ready to watch.',
    ),
    n(
      'workers',
      'workers',
      'Encoding Workers',
      'compute',
      3,
      'Create bitrate and resolution variants asynchronously.',
      'Encode once for many network conditions and devices.',
      'Encoding consumes compute and can fail partially.',
      'ASYNC BOUNDARY',
    ),
    n(
      'analytics',
      'services',
      'Playback Analytics',
      'events',
      5,
      'Aggregates startup, buffer, and quality signals.',
      'Measure user experience separately from segment delivery.',
      'Telemetry should not block playback.',
    ),
  ],
  scenarios: [
    flow(
      'playback',
      'Play Movie',
      'Authorize playback, fetch a manifest, then stream directly from the edge.',
      'The control plane chooses what to play; the media plane carries the bytes.',
      [
        s(
          'client',
          'gateway',
          'Start playback',
          'Request a playback session for the selected title.',
          'Identity and title selection are control-plane data.',
          'Uncontrolled access.',
        ),
        s(
          'gateway',
          'service',
          'Create playback session',
          'Route the small request to playback control.',
          'Keep orchestration independent of media throughput.',
          'API bandwidth bottlenecks.',
        ),
        s(
          'service',
          'rights',
          'Check playback rights',
          'Validate subscription and region.',
          'A valid session still needs content authorization.',
          'Unauthorized playback.',
          'read',
          { parallelGroup: 'prepare' },
        ),
        s(
          'service',
          'metadata',
          'Read title metadata',
          'Fetch duration and prepared representations concurrently.',
          'Independent reads can overlap.',
          'Serial startup latency.',
          'read',
          { parallelGroup: 'prepare' },
        ),
        s(
          'service',
          'manifest',
          'Select manifest',
          'After both checks complete, choose permitted representations.',
          'Manifest selection depends on eligibility and media readiness.',
          'Unplayable stream choices.',
        ),
        s(
          'manifest',
          'client',
          'Return manifest and URLs',
          'The player receives segment locations, not the movie bytes.',
          'Players can fetch and adapt independently.',
          'Control-plane overload.',
          'ack',
        ),
        s(
          'client',
          'cdn',
          'Request media segment',
          'Fetch a representation directly from the media edge.',
          'Nearby cached bytes reduce startup time.',
          'Long-distance bandwidth.',
          'media',
        ),
        s(
          'cdn',
          'storage',
          'Cold edge: fill from origin',
          'Retrieve an absent encoded segment.',
          'An edge cache is not the only copy.',
          'Cold-content misses.',
          'cache-miss',
          { excludeWhen: ['cache-hit'] },
        ),
        s(
          'storage',
          'cdn',
          'Cache the segment',
          'Transfer encoded bytes to the edge.',
          'Subsequent viewers can reuse this transfer.',
          'Repeated origin load.',
          'media',
          { excludeWhen: ['cache-hit'] },
        ),
        s(
          'cdn',
          'client',
          'Stream playable bytes',
          'Deliver the selected segment directly to the player.',
          'The API gateway never carries the video payload.',
          'Centralized media bottlenecks.',
          'media',
        ),
        s(
          'client',
          'cdn',
          'Adapt to lower bitrate',
          'A degraded network makes the player request a smaller representation.',
          'Buffer health matters more than maximum quality.',
          'Playback stalls.',
          'media',
          { condition: 'network-degraded' },
        ),
        s(
          'client',
          'analytics',
          'Report playback health',
          'Send buffer and startup measurements asynchronously.',
          'Operational feedback must not block viewing.',
          'Invisible playback regressions.',
          'telemetry',
        ),
      ],
      ['normal', 'cache-hit', 'cache-miss', 'network-degraded'],
    ),
    flow(
      'seek',
      'Seek Video',
      'Use the manifest to jump to the segment covering a new playback time.',
      'Seeking changes segment selection; it does not restart the whole control path.',
      [
        s(
          'client',
          'client',
          'Resolve target time',
          'Locally read the timeline mapping in the already selected manifest.',
          'The player needs a segment boundary, not a database scan.',
          'Slow seeking.',
          'read',
        ),
        s(
          'client',
          'cdn',
          'Fetch target segment',
          'Request the encoded segment at the new position.',
          'Direct edge delivery still applies after a seek.',
          'API proxy overhead.',
          'media',
        ),
        s(
          'cdn',
          'client',
          'Resume playback',
          'Decode from a suitable boundary and refill the buffer.',
          'Compressed media cannot start at every arbitrary byte.',
          'Decoder discontinuity.',
          'media',
        ),
      ],
    ),
    flow(
      'upload',
      'Upload & Transcode',
      'Turn a source upload into a publishable set of representations.',
      'Upload success and playback readiness are separate states.',
      [
        s(
          'client',
          'upload',
          'Upload source video',
          'Send resumable chunks and verify integrity.',
          'Large transfers fail and restart.',
          'Repeated whole-file uploads.',
          'write',
        ),
        s(
          'upload',
          'events',
          'Source ready event',
          'Publish a completed upload for asynchronous processing.',
          'Encoding is slower than accepting an upload.',
          'Long-lived API requests.',
          'event',
        ),
        s(
          'events',
          'workers',
          'Schedule encodes',
          'Generate multiple bitrate and resolution variants.',
          'Players need choices for different networks.',
          'One-size-fits-all media.',
          'event',
        ),
        s(
          'workers',
          'storage',
          'Persist encoded segments',
          'Write validated representations to durable origin storage.',
          'Publication must not point at missing bytes.',
          'Broken playback.',
          'write',
        ),
        s(
          'workers',
          'metadata',
          'Publish readiness',
          'Commit playable metadata only after required encodes exist.',
          'A partially processed upload should not look complete.',
          'Premature publication.',
          'write',
        ),
        s(
          'metadata',
          'manifest',
          'Publish manifest',
          'Expose only ready representations to playback.',
          'The manifest is the contract between preparation and delivery.',
          'Missing segment references.',
          'event',
        ),
      ],
    ),
  ],
  variants: [
    {
      id: 'netflix',
      name: 'Netflix',
      summary:
        'Netflix Open Connect media delivery with a deliberately abstract playback control plane. Upload is modeled as a content preparation workflow, not a public Netflix feature.',
      era: 'Open Connect public overview; control plane conceptual',
      sources: [sources.netflix],
      overrides: {
        'rw-cdn': {
          label: 'Open Connect Appliance',
          technology: 'Netflix Open Connect',
          confidence: 'verified',
          sourceIds: ['netflix'],
          description:
            'Publicly documented appliances store encoded media and serve it directly to Netflix clients over HTTP/S.',
        },
      },
      edgeOverrides: { 'rw-cdn--rw-client': { confidence: 'verified', sourceIds: ['netflix'] } },
      scenarioOverrides: {
        upload: {
          name: 'Prepare Catalog Video',
          description:
            'An illustrative content preparation pipeline; not a Netflix user-upload feature.',
        },
      },
    },
    {
      id: 'youtube',
      name: 'YouTube',
      summary:
        'A conceptual upload, processing, and viewing pipeline based on public product behavior. Internal encoding and storage technology are not asserted.',
      era: 'Public upload behavior; infrastructure conceptual',
      sources: [sources.youtube],
      overrides: {
        'rw-upload': { label: 'Creator Upload', confidence: 'inferred', sourceIds: ['youtube'] },
        'rw-cdn': { label: 'Video Delivery Edge' },
      },
    },
  ],
} satisfies FamilyBlueprint;
