import type { ArchitectureFamily, CompanyOption } from './types';
const companies = (entries: [string, string, boolean][]): CompanyOption[] =>
  entries.map(([id, name, available]) => ({ id, name, available }));
export const families: ArchitectureFamily[] = [
  {
    id: 'social',
    name: 'Social Feed',
    icon: 'users',
    description: 'Follow a post from creation to a personalized timeline.',
    defaultScenario: 'home-feed',
    genericArchitecture: 'generic',
    keyChallenges: [
      'Read latency vs write amplification',
      'Celebrity fanout',
      'Ranking and freshness',
    ],
    scenarioNames: ['Load Home Feed', 'Create Post', 'Celebrity Post'],
    companies: companies([
      ['instagram', 'Instagram', true],
      ['facebook', 'Facebook', true],
      ['twitter', 'X / Twitter', false],
      ['linkedin', 'LinkedIn', false],
      ['tiktok', 'TikTok', false],
    ]),
  },
  {
    id: 'chat',
    name: 'Messaging',
    icon: 'message-circle',
    description: 'Durable messages, live connections, and offline recipients.',
    defaultScenario: 'send-message',
    genericArchitecture: 'generic',
    keyChallenges: ['Ordering and deduplication', 'Offline delivery', 'Large-group fanout'],
    scenarioNames: ['Send Message', 'Group Message', 'Reconnect Client'],
    companies: companies([
      ['discord', 'Discord', true],
      ['whatsapp', 'WhatsApp', false],
      ['slack', 'Slack', false],
      ['telegram', 'Telegram', false],
      ['messenger', 'Messenger', false],
    ]),
  },
  {
    id: 'video',
    name: 'Video Streaming',
    icon: 'radio',
    description: 'The control request is small. The media path is enormous.',
    defaultScenario: 'playback',
    genericArchitecture: 'generic',
    keyChallenges: ['Edge locality', 'Adaptive bitrate', 'Content preparation'],
    scenarioNames: ['Play Movie', 'Seek Video', 'Upload & Transcode'],
    companies: companies([
      ['netflix', 'Netflix', true],
      ['youtube', 'YouTube', true],
      ['twitch', 'Twitch', false],
      ['disney', 'Disney+', false],
      ['prime', 'Prime Video', false],
    ]),
  },
  {
    id: 'ride',
    name: 'Ride Sharing / Geo',
    icon: 'route',
    description: 'Match moving supply to a transactional ride request.',
    defaultScenario: 'request-ride',
    genericArchitecture: 'generic',
    keyChallenges: ['Fresh locations', 'Exclusive driver assignment', 'Matching latency'],
    scenarioNames: ['Request Ride', 'Driver Location Update', 'Complete Trip'],
    companies: companies([
      ['uber', 'Uber', true],
      ['lyft', 'Lyft', false],
      ['grab', 'Grab', false],
      ['doordash', 'DoorDash', false],
      ['maps', 'Google Maps', false],
    ]),
  },
  {
    id: 'commerce',
    name: 'E-commerce',
    icon: 'layers',
    description: 'Coordinate inventory, payment, and fulfillment safely.',
    defaultScenario: 'place-order',
    genericArchitecture: 'generic',
    keyChallenges: ['Inventory contention', 'Partial failure', 'Idempotent checkout'],
    scenarioNames: ['Place Order', 'Search Product', 'Add to Cart'],
    companies: companies([
      ['amazon', 'Amazon-style', true],
      ['shopify', 'Shopify', false],
      ['ebay', 'eBay', false],
      ['walmart', 'Walmart', false],
      ['flipkart', 'Flipkart', false],
    ]),
  },
  {
    id: 'search',
    name: 'Search Engine',
    icon: 'search',
    description: 'Build the index offline; fan queries out in parallel.',
    defaultScenario: 'search-query',
    genericArchitecture: 'generic',
    keyChallenges: ['Index freshness', 'Shard fanout', 'Relevance'],
    scenarioNames: ['Search Query', 'Crawl & Index', 'Autocomplete'],
    companies: companies([
      ['google', 'Google-style Search', true],
      ['bing', 'Bing', false],
      ['elasticsearch', 'Elasticsearch', false],
      ['algolia', 'Algolia', false],
      ['opensearch', 'OpenSearch', false],
    ]),
  },
  {
    id: 'files',
    name: 'File Storage / Sync',
    icon: 'cloud',
    description: 'Move missing chunks, commit metadata, synchronize devices.',
    defaultScenario: 'upload-file',
    genericArchitecture: 'generic',
    keyChallenges: ['Durable bytes vs metadata', 'Conflicts', 'Efficient transfers'],
    scenarioNames: ['Upload File', 'Sync Device', 'Resolve Conflict'],
    companies: companies([
      ['dropbox', 'Dropbox', true],
      ['drive', 'Google Drive', false],
      ['onedrive', 'OneDrive', false],
      ['icloud', 'iCloud Drive', false],
      ['box', 'Box', false],
    ]),
  },
  {
    id: 'music',
    name: 'Music / Audio',
    icon: 'radio',
    description: 'Stream audio separately from playlists and recommendations.',
    defaultScenario: 'play-song',
    genericArchitecture: 'generic',
    keyChallenges: ['Playback continuity', 'Rights and region', 'Personalization'],
    scenarioNames: ['Play Song', 'Load Playlist', 'Generate Recommendations'],
    companies: companies([
      ['spotify', 'Spotify-style', true],
      ['apple', 'Apple Music', false],
      ['youtube-music', 'YouTube Music', false],
      ['soundcloud', 'SoundCloud', false],
      ['amazon-music', 'Amazon Music', false],
    ]),
  },
  {
    id: 'gaming',
    name: 'Real-time Gaming',
    icon: 'zap',
    description: 'Validate player inputs in a regional authoritative simulation.',
    defaultScenario: 'join-match',
    genericArchitecture: 'generic',
    keyChallenges: ['Tick budgets', 'Prediction and reconciliation', 'Regional latency'],
    scenarioNames: ['Join Match', 'Player Movement', 'Match Result'],
    companies: companies([
      ['fortnite', 'Fortnite-style', true],
      ['roblox', 'Roblox', false],
      ['valorant', 'Valorant', false],
      ['minecraft', 'Minecraft Realms', false],
      ['mmo', 'Large-scale MMO', false],
    ]),
  },
  {
    id: 'payments',
    name: 'Payments / Fintech',
    icon: 'lock',
    description: 'Track money through authorization, capture, and settlement.',
    defaultScenario: 'make-payment',
    genericArchitecture: 'generic',
    keyChallenges: ['Duplicate effects', 'Uncertain processor outcomes', 'Ledger reconciliation'],
    scenarioNames: ['Make Payment', 'Capture Payment', 'Refund Payment', 'Reconcile'],
    companies: companies([
      ['stripe', 'Stripe-style', true],
      ['paypal', 'PayPal', false],
      ['adyen', 'Adyen', false],
      ['square', 'Square', false],
      ['razorpay', 'Razorpay', false],
    ]),
  },
];
export const getFamily = (id: string) => families.find((f) => f.id === id);
